image: aergus/latex

stages:
  - build

assistant-script:
  stage: build
  script:
    - apt-get update
    - apt-get -y install ghostscript
    - cd script_assistant
    - latexmk -Werror -f -pdf -silent -shell-escape -interaction=nonstopmode -e '$max_repeat=10' -output-directory="build" AirMassflowSensorAssistent.tex
  artifacts:
    when: always
    paths:
      - "script_assistant/build/*.log"
      - "script_assistant/build/*.pdf"
    expire_in: 10 yrs
    
student-script:
  stage: build
  script:
    - apt-get update
    - apt-get -y install ghostscript
    - cd script_student
    - latexmk -Werror -f -pdf -silent -shell-escape -interaction=nonstopmode -e '$max_repeat=10' -output-directory="build" AirMassflowSensorStudent.tex
  artifacts:
    when: always
    paths:
      - "script_student/build/*.log"
      - "script_student/build/*.pdf"
    expire_in: 10 yrs
