disturbance_rejection:
  delay: 15
  deviation: 40
  duration: 20
  temp_sensors_switched: 1
general:
  interval: 120
  nominal_mass_flow_rate: 60
  t_sampling: 0.25
  temperature_difference_set_point: 15
measurement:
  massflow_estimate:
    c_p: 1006.0
    massflow_SI2SLM: 46432
    resistance: 11
    voltage: 24
  temperature:
    maximum_calibration_offset: 0.5
pid_controller:
  d_limit: 1
  i_limit: 0.2
  p_limit: 1
  sample_time: 0.3
reference_tracking:
  interval: 60
safety:
  lower_flow_limit: 15
  upper_temperature_limit: 60
serials:
  EKS: EKS23Z50PQ
  Heater: AM01ZB7J
  SFC: FT1PXV63
